### ISSUE TITLE
Paid for one month of extra features and I’m still restricted to free content only

### ISSUE THREAD

**Issue by theGoose-lab** [gtjamesa/ge-tracker-app#124] opened 2021-01-19 23:58 UTC
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gtjamesa** [comment] 2021-01-20 06:07
Duplicate of #123

**Closed as completed by gtjamesa** 2021-01-20 06:07 UTC
